/**
 * Prisma client singleton for the socket server process.
 *
 * This is a copy of the main app's `src/lib/prisma.ts`, pointed at this
 * project's own copy of the generated client. `schema.prisma`'s `output`
 * is `../src/generated/prisma` — `prisma generate` always writes there,
 * never to a bare `generated/prisma` at the project root. A previous
 * version of this file imported from that wrong root-level path, which
 * doesn't get regenerated by anything and silently drifts out of date
 * (missing whole models added later, like ChatMessage) — that mismatch
 * caused every chat-message save to fail with `Cannot read properties of
 * undefined (reading 'create')`. Fixed once before; if this regresses
 * again, check whether a stale `generated/prisma` folder has reappeared
 * at the project root and delete it — its mere existence is what made
 * the wrong import path "work" (as in: resolve to *something*) instead
 * of failing loudly at import time.
 */
import { PrismaClient } from "../src/generated/prisma/client.js";
import { PrismaPg } from "@prisma/adapter-pg";

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined;
};

function createPrismaClient(): PrismaClient {
  const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
  return new PrismaClient({ adapter });
}

export const prisma: PrismaClient = globalForPrisma.prisma ?? createPrismaClient();

if (process.env.NODE_ENV !== "production") {
  globalForPrisma.prisma = prisma;
}
